# numbers_to_tex.R — converts output/repro/paper_numbers.csv into LaTeX macros
# (manuscript/numbers.tex) for the ORBIS solvency application. The paper
# references ONLY these macros, so text and pipeline cannot drift apart.
# Run after code/03_panel_e2tree_orbis.R.

args <- commandArgs(trailingOnly = FALSE)
script_path <- sub("^--file=", "", grep("^--file=", args, value = TRUE))
BASE <- if (length(script_path)) dirname(dirname(normalizePath(script_path))) else normalizePath("..")

nums <- read.csv(file.path(BASE, "output", "repro", "paper_numbers.csv"),
                 stringsAsFactors = FALSE)

# key (pipeline) -> macro (LaTeX, letters only)
map <- c(
  n_obs = "nObs", n_firms = "nFirms", n_countries = "nCountries",
  year_min = "yearMin", year_max = "yearMax",
  icc_solv = "iccSolv", icc_solv_poolwide = "iccSolvPool",
  n_firms_pool = "nFirmsPool",
  c_b_solv = "cBsolv", icc_star_solv = "iccStarSolv",
  delta_b_solv = "deltaBsolv", sigma_w2_solv = "sigmaWsqSolv",
  c_b_sim = "cBsim", icc_star_sim = "iccStarSim",
  between_root_thr = "betweenRootThr", between_low_leaf = "betweenLowLeaf",
  within_low_leaf_abs = "withinLowLeafAbs",
  between_fidelity = "betweenFid", within_fidelity = "withinFid",
  panel_r2 = "panelR", panel_cor2 = "panelCor", within_signal = "withinSignal",
  between_leaves = "betweenLeaves", within_leaves = "withinLeaves",
  between_vars = "betweenVars", within_vars = "withinVars",
  within_oob_r2 = "withinOobR", gap_bound = "gapBound",
  decomp_r2_within = "decompWithinR", decomp_r2_between = "decompBetweenR",
  pooled_r2_vs_y = "pooledR", pooled_cor2_vs_y = "pooledCor",
  pooled_fid_vs_ens = "pooledFid", pooled_leaves = "pooledLeaves",
  pooled_r2_within = "pooledWithinR", pooled_r2_between = "pooledBetweenR",
  matched_r2_vs_y = "matchedR", matched_leaves = "matchedLeaves",
  matched_r2_within = "matchedWithinR", matched_r2_between = "matchedBetweenR",
  decomp_leaves_total = "decompLeaves",
  aug_r2_vs_y = "augR", aug_r2_within = "augWithinR", aug_r2_between = "augBetweenR",
  aug_splits_bw = "augBw", aug_splits_wn = "augWn", aug_top10_bw = "augTopBw",
  aug_leaves = "augLeaves",
  ens_root_bw_share = "ensRootBw", ens_share_bw = "ensShareBw",
  prox_between_real = "proxBetweenReal",
  prox_between_range = "proxBetweenRange", prox_icc_range = "proxIccRange",
  pooledtarget_r2 = "pooledTargetR", pooledtarget_within_fid = "pooledTargetWithinFid",
  bridge_r2 = "bridgeR", icc_pooled_preds = "iccPooledPreds",
  twoway_r2 = "twowayR", twoway_within_fid = "twowayWithinFid",
  twoway_trend_cor = "twowayTrendCor",
  oot_n = "ootN", oot_r2 = "ootR", oot_cor2 = "ootCor",
  oot_r2_within = "ootWithinR", oot_r2_between = "ootBetweenR",
  oot_train_max = "ootTrainMax", oot_test_min = "ootTestMin",
  shap_icc_mean = "shapIccMean", shap_icc_min = "shapIccMin",
  shap_raw_top1 = "shapRawTopOne", shap_raw_top2 = "shapRawTopTwo",
  shap_raw_top3 = "shapRawTopThree",
  shap_wn_top1 = "shapWnTopOne", shap_wn_top2 = "shapWnTopTwo",
  shap_wn_top3 = "shapWnTopThree",
  shap_sim_raw = "shapSimRaw", shap_sim_aug = "shapSimAug",
  shap_sim_sep = "shapSimSep",
  icc_sim = "iccSim",
  sim_pooled_vars = "simPooledVars", sim_between_vars = "simBetweenVars",
  sim_within_vars = "simWithinVars",
  sim_pooled_fid = "simPooledFid", sim_between_fid = "simBetweenFid",
  sim_within_fid = "simWithinFid",
  sim_inter_r2_g0 = "simInterRgZero", sim_inter_r2_g05 = "simInterRgHalf",
  sim_inter_r2_g1 = "simInterRgOne",
  reduced_within_fid = "reducedWithinFid",
  vimp_top1 = "vimpTopOne", vimp_top2 = "vimpTopTwo", vimp_top3 = "vimpTopThree"
)

tex_escape <- function(x) {
  x <- gsub("_", "\\\\_", x); x <- gsub("\\+-", "$\\\\pm$", x); x <- gsub("%", "\\\\%", x)
  neg <- grepl("^-[0-9.]+$", x); x[neg] <- paste0("\\ensuremath{", x[neg], "}"); x
}

lines <- c("% AUTO-GENERATED by code/numbers_to_tex.R from output/repro/paper_numbers.csv",
           "% Do not edit by hand: re-run code/03_panel_e2tree_orbis.R + code/numbers_to_tex.R.")
for (i in seq_len(nrow(nums))) {
  key <- nums$key[i]; if (!key %in% names(map)) next
  lines <- c(lines, sprintf("\\newcommand{\\%s}{%s}", map[[key]], tex_escape(nums$value[i])))
}
missing <- setdiff(unname(map), sub("^\\\\newcommand\\{\\\\([A-Za-z]+)\\}.*$", "\\1",
                                    grep("newcommand", lines, value = TRUE)))
if (length(missing)) warning("Macros without a pipeline value: ", paste(missing, collapse = ", "))
writeLines(lines, file.path(BASE, "manuscript", "numbers.tex"))
