# 08_numbers_v2.R — LaTeX macros for the quantities added by the v2 revision.
# Same discipline as code/numbers_to_tex.R: the manuscript references only
# macros, so text and pipeline cannot drift apart. Reads the two result files
# written by code/05_budget59.R and code/06_within_no_age.R.
# Output: manuscript/manuscript_DSS_v2/numbers_budget.tex
# Usage: Rscript code/08_numbers_v2.R   (after 05 and 06)

BASE <- normalizePath(file.path(dirname(sub("^--file=", "",
  grep("^--file=", commandArgs(trailingOnly = FALSE), value = TRUE))), ".."))
IN  <- file.path(BASE, "output", "budget59")
TEX <- file.path(BASE, "manuscript", "manuscript_DSS_v2", "numbers_budget.tex")

g <- read.csv(file.path(IN, "budget59_grid.csv"), stringsAsFactors = FALSE)
a <- read.csv(file.path(IN, "within_no_age.csv"), stringsAsFactors = FALSE)

nec <- read.csv(file.path(BASE, "output", "repro", "necessity.csv"), stringsAsFactors = FALSE)
BUDGET <- nec$leaves[grep("^\\(d\\)", nec$approach)]

sw   <- g[g$tag == "budget sweep", ]
lad  <- g[g$tag == "impurity ladder", ]
# The ladder holds the maximum depth and the minimum node size fixed and varies
# only the total-impurity threshold. Every row yields the same tree, so over the
# range tested that rule never binds; the macros report the range, not a
# crossing point, because none was observed.
ladder_flat <- length(unique(lad$leaves)) == 1 &&
  diff(range(lad$r2_vs_y)) < 1e-9
texnum <- function(x) if (x >= 1e-3) sub("0+$", "", sprintf("%.4f", x)) else
  sprintf("\\ensuremath{10^{%d}}", round(log10(x)))
cand <- sw[sw$leaves <= BUDGET, ]
sel  <- cand[order(-cand$leaves, -cand$r2_vs_y), ][1, ]      # see 07_figures_v2.R
best <- sw[which.max(sw$r2_within), ]                        # most favourable to pooled

fmt3 <- function(x) sprintf("%.3f", x)
nm_num <- c(
  budgetLeaves      = sel$leaves,
  budgetDepth       = sel$depth,
  budgetR           = fmt3(sel$r2_vs_y),
  budgetWithinR     = fmt3(sel$r2_within),
  budgetBetweenR    = fmt3(sel$r2_between),
  budgetNconfig     = nrow(sw),
  budgetLeafMin     = min(sw$leaves),
  budgetLeafMax     = max(sw$leaves),
  budgetBestWithinR = fmt3(best$r2_within),
  budgetBestLeaves  = best$leaves,
  budgetWorstWithinR= fmt3(min(sw$r2_within)),
  noAgeWithinFid    = fmt3(a$within_fidelity[a$run == "no_age"]),
  noAgeWithinLeaves = a$within_leaves[a$run == "no_age"],
  noAgeR            = fmt3(a$panel_r2[a$run == "no_age"]),
  noAgeWithinR      = fmt3(a$r2_within[a$run == "no_age"]),
  shapSetWithinFid  = fmt3(a$within_fidelity[a$run == "no_age_size"]),
  budgetImpMax      = texnum(max(lad$impTotal)),
  budgetImpMin      = texnum(min(lad$impTotal)),
  budgetImpHeld     = texnum(unique(sw$impTotal)[1])
)

# sanity: the reproduction rows must still match the published configurations
pub <- g[grepl("published", g$tag), ]   # the two reproduction rows only
stopifnot(nrow(pub) == 2,
          pub$leaves[1] == 14, pub$leaves[2] == 18,
          abs(pub$r2_within[1] - (-0.120)) < 5e-4,
          abs(pub$r2_within[2] - (-0.119)) < 5e-4)
stopifnot(abs(a$within_fidelity[a$run == "full"] - 0.477) < 5e-4)
stopifnot(nrow(lad) > 1, length(unique(sw$impTotal)) == 1)
# the text says the threshold does not bind over the tested range; assert it
stopifnot(ladder_flat)

# same convention as code/numbers_to_tex.R: negatives are wrapped so the minus
# sign is typeset as a minus and not as a hyphen
esc <- function(x) { neg <- grepl("^-[0-9.]+$", x)
                     x[neg] <- paste0("\\ensuremath{", x[neg], "}"); x }
nm <- names(nm_num)
num <- esc(as.character(nm_num))

lines <- c(
  "% AUTO-GENERATED by code/08_numbers_v2.R from output/budget59/*.csv",
  "% Do not edit by hand: re-run code/05_budget59.R + code/06_within_no_age.R,",
  "% then code/08_numbers_v2.R. Holds ONLY the budget-sweep and no-age quantities;",
  "% numbers.tex and numbers_pooled_target.tex hold the rest. All three are \\input",
  "% by manuscript.tex: none of them is a newer version of another.",
  sprintf("\\newcommand{\\%s}{%s}", nm, num))
writeLines(lines, TEX)
cat("written:", TEX, "\n"); writeLines(lines[-(1:3)])

# ---------------------------------------------------------------------------
# Supplementary tables
# ---------------------------------------------------------------------------
SUPP <- file.path(BASE, "manuscript", "manuscript_DSS_v2", "supp")
rng <- function(x, d = 3) if (diff(range(x)) < 10^(-d) / 2)
  sprintf(paste0("%.", d, "f"), x[1]) else
  sprintf(paste0("%.", d, "f--%.", d, "f"), min(x), max(x))

# (1) leaf-budget sweep, aggregated by depth cap
agg <- do.call(rbind, lapply(split(sw, sw$level), function(z) data.frame(
  level = z$level[1],
  leaves = if (min(z$leaves) == max(z$leaves)) as.character(z$leaves[1]) else
    sprintf("%d--%d", min(z$leaves), max(z$leaves)),
  r2 = rng(z$r2_vs_y),
  # negative range: "--" would collide with the leading minus sign
  within = if (diff(range(z$r2_within)) < 5e-4) sprintf("$%.3f$", z$r2_within[1]) else
    sprintf("$%.3f$ to $%.3f$", min(z$r2_within), max(z$r2_within)),
  between = rng(z$r2_between))))
agg <- agg[order(agg$level), ]
writeLines(c("\\begin{tabular}{rlrrr}", "\\toprule",
  "Maximum depth & Terminal nodes & $R^2$ total & $R^2_{\\text{within}}$ & $R^2_{\\text{between}}$ \\\\",
  "\\midrule",
  sprintf("%d & %s & %s & %s & %s \\\\", agg$level, agg$leaves, agg$r2,
          agg$within, agg$between),
  "\\bottomrule", "\\end{tabular}"),
  file.path(SUPP, "tab_budget.tex"))

# (2) the firm-age robustness refits
lab <- c(full = "all eleven predictors",
         no_age = "firm age removed",
         no_age_size = "firm age and log total assets removed")
a2 <- a[match(names(lab), a$run), ]
writeLines(c("\\begin{tabular}{lrrrr}", "\\toprule",
  "Predictor set & Within leaves & Within fidelity & $R^2$ total & $R^2_{\\text{within}}$ \\\\",
  "\\midrule",
  sprintf("%s & %d & %.3f & %.3f & %.3f \\\\", lab, a2$within_leaves,
          a2$within_fidelity, a2$panel_r2, a2$r2_within),
  "\\bottomrule", "\\end{tabular}"),
  file.path(SUPP, "tab_noage.tex"))

cat("written:", file.path(SUPP, "tab_budget.tex"), "and tab_noage.tex\n")
